#%RAML 0.8
title: Foo
version: 0.1
mediaType: application/json
documentation:
  - title : Foo
    content : A String
schemas:
    - user: |
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "id": "http://jsonschema.net",
          "type": "object",
          "properties": {
            "username": {
              "id": "http://jsonschema.net/username",
              "type": "string"
            },
            "password": {
              "id": "http://jsonschema.net/password",
              "type": "string"
            }
          },
          "required": [
            "username",
            "password"
          ]
        }
/cs:
  /login:
    post:
      responses:
        200:
          body:
            application/json:
              schema: user
