#%RAML 0.8
---
title: Test send form data
documentation:
  - title: Some title
    content: Some content
/sendFormData:
  post:
   body:
     application/x-www-form-urlencoded:
       formParameters:
         param1:
            description: |
              parameter number 1.
            type: string
            required: true
         param2:
            description: |
              parameter number 2.
            type: integer
            required: false
