#%RAML 1.0
title: Foo
version: 0.1
mediaType: application/json
documentation:
  - title : Foo
    content : A String
/foo:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              { "message": "foo" }
/foo/a:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              { "message": "foo" }
/foo/b:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              { "message": "foo" }

